'use strict';
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function sharedLayout(){
 const header=$('[data-header]');if(header)header.innerHTML='<a class="skip" href="#main">Skip to content</a><header class="header shell"><a class="brand" href="index.html"><span class="monogram">hs<span>↗</span></span><span>HAPPY SINGH<small>3D ARTIST & MULTIDISCIPLINARY CREATIVE</small></span></a><button class="menu" aria-label="Open navigation" aria-expanded="false" aria-controls="nav">☰</button><nav id="nav"><a href="index.html#work">Selected work</a><a href="portfolio.html?discipline=3d">3D portfolio</a><a href="tools.html">Tools & plugins</a><a href="index.html#about">About</a></nav><a class="contact-nav" href="index.html#contact">Let’s talk <span>↗</span></a></header>';
 const footer=$('[data-footer]');if(footer)footer.innerHTML='<footer class="shell footer"><a class="footer-brand" href="index.html">HAPPY SINGH<span>3D</span></a><span>© <span data-year></span> Harpreet Singh Uppal</span><a href="tools.html">Tools & plugins ↗</a><a href="index.html#contact">Get in touch ↗</a></footer>';
 document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());
 const menu=$('.menu');if(menu){menu.addEventListener('click',()=>{const open=$('#nav').classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');});document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});}
}
function closeMenu(){const nav=$('#nav'),menu=$('.menu');if(nav)nav.classList.remove('open');if(menu){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');}}
sharedLayout();
function renderProjects(target,projects){target.replaceChildren();for(const p of projects){const card=document.createElement('article');card.className='project-card';card.innerHTML=`<button class="project-image" data-project="${p.id}" aria-label="Explore ${escapeHTML(p.title)}"><img src="assets/${p.image}" alt="${escapeHTML(p.title)} — portfolio preview" loading="lazy" width="640" height="420"><span class="project-open" aria-hidden="true">↗</span></button><div class="project-meta"><span>${escapeHTML(p.category)}</span><h3><button data-project="${p.id}">${escapeHTML(p.title)}</button></h3></div>`;target.append(card);}}
function renderProducts(target,products){target.replaceChildren();for(const p of products){const article=document.createElement('article');article.className='product-card';article.innerHTML=`<div class="product-icon-row"><span class="product-symbol" aria-hidden="true">${escapeHTML(p.symbol)}</span><span class="product-platform">${escapeHTML(p.tag)}</span></div><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.detail)}</p><a class="quiet-link" href="${p.url}" target="_blank" rel="noopener noreferrer">View on Gumroad ↗</a>`;target.append(article);}}
function originalMediaURL(p){if(!p.embed)return SITE.portfolios[p.type].url;if(p.embed.includes('drive.google.com'))return p.embed.replace('/preview','/view');return p.embed;}
function openProject(id){const p=PROJECTS.find(p=>p.id===id);if(!p)return;let dialog=$('#project-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='project-dialog';dialog.className='project-dialog';document.body.append(dialog);}dialog.innerHTML=`<div class="dialog-head"><h2 id="project-title">${escapeHTML(p.title)}</h2><button class="close-dialog" aria-label="Close project">×</button></div><div class="dialog-body"><div class="detail-media"><img src="assets/${p.image}" alt="${escapeHTML(p.title)}"></div><div class="detail-info"><span class="eyebrow">${escapeHTML(p.category)}</span><p>${escapeHTML(p.description)}</p><span class="eyebrow">FOCUS</span><p>${escapeHTML(p.role)}</p><span class="eyebrow">WORKFLOW</span><p>${escapeHTML(p.tools)}</p>${p.embed?'<button class="button" id="play-project">▷ Watch the recording</button><small>Loads the original external video player.</small>':''}<a class="quiet-link" href="${originalMediaURL(p)}" target="_blank" rel="noopener noreferrer">${p.embed?'Open original media':'View the design portfolio'} ↗</a></div></div>`;dialog.setAttribute('aria-labelledby','project-title');dialog.querySelector('.close-dialog').onclick=()=>dialog.close();if(p.embed)$('#play-project').onclick=()=>{const frame=document.createElement('iframe');frame.src=p.embed;frame.title=p.title;frame.allow='fullscreen; autoplay; encrypted-media';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';dialog.querySelector('.detail-media').replaceChildren(frame);$('#play-project').disabled=true;$('#play-project').textContent='Player loaded';};dialog.onclose=()=>dialog.querySelectorAll('iframe').forEach(frame=>frame.remove());dialog.showModal();}
document.addEventListener('click',e=>{const button=e.target.closest('[data-project]');if(button)openProject(button.dataset.project);});
if($('#selected-grid')){let type='3d';function showSelected(){renderProjects($('#selected-grid'),PROJECTS.filter(p=>p.type===type).slice(0,3));$('#discipline-link').href=`portfolio.html?discipline=${type}`;$('#discipline-link').textContent=`Explore the ${type==='3d'?'3D':type==='design'?'design':'video'} portfolio ↗`;document.querySelectorAll('[data-type]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.type===type)));}document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{type=b.dataset.type;showSelected();});showSelected();}
if($('#product-grid'))renderProducts($('#product-grid'),PRODUCTS.slice(0,3));
const params=new URLSearchParams(location.search);const requestedType=params.get('discipline');const currentType=Object.hasOwn(SITE.portfolios,requestedType)?requestedType:'3d';
if($('#portfolio-grid')){
 const info=SITE.portfolios[currentType];document.title=`${info.name} — Happy Singh`;$('#portfolio-title').textContent=info.name;$('#portfolio-description').textContent=info.description;$('#portfolio-kicker').textContent=info.subtitle;$('#portfolio-original').href=info.url;
 const items=PROJECTS.filter(p=>p.type===currentType);const categories=['All work',...new Set(items.map(p=>p.category))];let category='All work';const filters=$('#gallery-filters');
 function showCategory(){const visible=items.filter(p=>category==='All work'||p.category===category);renderProjects($('#portfolio-grid'),visible);$('#collection-count').textContent=`${visible.length} selected ${visible.length===1?'project':'projects'} · Full collection available in the original portfolio`;filters.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.textContent===category)));}
 for(const value of categories){const b=document.createElement('button');b.textContent=value;b.onclick=()=>{category=value;showCategory();};filters.append(b);}showCategory();
 $('#preview-original').onclick=()=>loadWebsite(info.url,`${info.name} — original portfolio`);
 if(currentType==='3d'){$('#preview-v4').hidden=false;$('#preview-v4').onclick=()=>loadWebsite(info.alternate,'Earlier 3D portfolio — v4');}
}
function loadWebsite(url,title){const host=$('#website-viewer');if(!host)return;host.hidden=false;host.innerHTML=`<div class="viewer-toolbar"><span>${escapeHTML(title)}</span><div><a href="${url}" target="_blank" rel="noopener noreferrer">Open in new tab ↗</a><button id="close-viewer" aria-label="Close embedded website">×</button></div></div><iframe class="viewer-frame" title="${escapeHTML(title)}" src="${url}" allow="fullscreen; autoplay" referrerpolicy="strict-origin-when-cross-origin"></iframe><p class="viewer-fallback">If the embedded site doesn’t load or feels cramped, use “Open in new tab” above. The original website keeps its own layout and controls.</p>`;$('#close-viewer').onclick=()=>{host.replaceChildren();host.hidden=true;};host.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
if($('#launch-toolkit'))$('#launch-toolkit').onclick=()=>loadWebsite(SITE.toolkit,'Toolkit — 3D Artist Suite');
if($('#all-products'))renderProducts($('#all-products'),PRODUCTS);
