// A procedural 3D form for the site, not a claimed client or portfolio project.
'use strict';
(()=>{const canvas=document.querySelector('#form-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;let angleX=.48,angleY=.48,wire=false,drag=null;const rings=140,sides=26,vertices=[];
 const center=t=>[(2+.55*Math.cos(3*t))*Math.cos(2*t),(2+.55*Math.cos(3*t))*Math.sin(2*t),.8*Math.sin(3*t)];
 const norm=v=>{const n=Math.hypot(...v)||1;return v.map(x=>x/n);};const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
 for(let i=0;i<rings;i++){const t=i/rings*Math.PI*2,c=center(t),next=center(t+.001),tangent=norm(next.map((v,k)=>v-c[k])),n=norm(cross(tangent,[0,0,1])),b=cross(tangent,n);for(let j=0;j<sides;j++){const v=j/sides*Math.PI*2;vertices.push(c.map((x,k)=>x+.47*(Math.cos(v)*n[k]+Math.sin(v)*b[k])));}}
 function transformed(p){const cy=Math.cos(angleY),sy=Math.sin(angleY),cx=Math.cos(angleX),sx=Math.sin(angleX),x=p[0]*cy+p[2]*sy,z=-p[0]*sy+p[2]*cy;return[x,p[1]*cx-z*sx,p[1]*sx+z*cx];}
 function draw(){const rect=canvas.getBoundingClientRect(),w=rect.width,h=rect.height,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const scale=Math.min(w,h)*.143,points=vertices.map(transformed);const project=p=>{const perspective=9/(9-p[2]);return[w/2+p[0]*scale*perspective,h*.47-p[1]*scale*perspective];};
 const shadow=ctx.createRadialGradient(w*.5,h*.76,5,w*.5,h*.76,w*.32);shadow.addColorStop(0,'rgba(0,0,0,.4)');shadow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=shadow;ctx.save();ctx.translate(0,h*.53);ctx.scale(1,.3);ctx.fillRect(0,0,w,h);ctx.restore();
 const faces=[];for(let i=0;i<rings;i++)for(let j=0;j<sides;j++){const ids=[i*sides+j,((i+1)%rings)*sides+j,((i+1)%rings)*sides+(j+1)%sides,i*sides+(j+1)%sides],ps=ids.map(n=>points[n]),n=norm(cross(ps[1].map((v,k)=>v-ps[0][k]),ps[3].map((v,k)=>v-ps[0][k])));faces.push({ps,z:ps.reduce((s,p)=>s+p[2],0)/4,n});}faces.sort((a,b)=>a.z-b.z);
 for(const f of faces){const p=f.ps.map(project);ctx.beginPath();p.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();if(wire){ctx.strokeStyle=`rgba(197,187,160,${Math.max(.1,.25+(f.z+3)*.055)})`;ctx.lineWidth=.55;ctx.stroke();}else{const light=Math.max(0,f.n[0]*.35-f.n[1]*.55-f.n[2]*.75),rim=Math.pow(Math.max(0,-f.n[2]),10)*30;const base=55+light*112+rim;ctx.fillStyle=`rgb(${Math.round(base*1.12)},${Math.round(base*1.02)},${Math.round(base*.81)})`;ctx.fill();ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=.6;ctx.stroke();}}
 }
 canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag)return;angleY+=(e.clientX-drag.x)*.008;angleX+=(e.clientY-drag.y)*.008;drag={x:e.clientX,y:e.clientY};draw();});for(const evt of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(evt,()=>drag=null);
 canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')angleY-=.12;if(e.key==='ArrowRight')angleY+=.12;if(e.key==='ArrowUp')angleX-=.12;if(e.key==='ArrowDown')angleX+=.12;draw();});
 for(const id of ['surface','wireframe'])document.querySelector('#'+id).onclick=()=>{wire=id==='wireframe';document.querySelector('#surface').setAttribute('aria-pressed',String(!wire));document.querySelector('#wireframe').setAttribute('aria-pressed',String(wire));draw();};new ResizeObserver(draw).observe(canvas);draw();})();
