window.PROJECTS = [
 {id:'character-rig',type:'3d',title:'Character rig',category:'Rigging',image:'character-rig_H3Lf29ETnzJ.png',description:'A Maya character rig demonstration, with controls and deformation shown in the original recording.',role:'Character rigging',tools:'Autodesk Maya',embed:'https://www-ccv.adobe.io/v1/player/ccv/H3Lf29ETnzJ/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View'},
 {id:'animation-04',type:'3d',title:'Character in motion',category:'Animation',image:'animation_04_I2WXjQ62nHL.png',description:'A character movement study presented from the Maya animation workspace. Open the recording to inspect the timing and motion.',role:'Character animation',tools:'Autodesk Maya',embed:'https://www-ccv.adobe.io/v1/player/ccv/I2WXjQ62nHL/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View'},
 {id:'particles-01',type:'3d',title:'Real-time particle study',category:'Real-time',image:'unity-particle_01_6mXRAp65_h9.png',description:'A real-time particle effects study from the existing Unity work collection.',role:'Particle effects',tools:'Unity',embed:'https://www-ccv.adobe.io/v1/player/ccv/6mXRAp65_h9/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View'},
 {id:'animation-01',type:'3d',title:'Animation study / 01',category:'Animation',image:'animation_01_Q3o3ImhDRtn.png',description:'An animation study from my existing portfolio. The original recording is available to watch here.',role:'Animation',tools:'3D animation workflow',embed:'https://www-ccv.adobe.io/v1/player/ccv/Q3o3ImhDRtn/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View'},
 {id:'animation-03',type:'3d',title:'Animation study / 03',category:'Animation',image:'animation_03_M_Jy8D8xtui.png',description:'A further character animation study, collected here with the other motion work.',role:'Animation',tools:'3D animation workflow',embed:'https://www-ccv.adobe.io/v1/player/ccv/M_Jy8D8xtui/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View'},
 {id:'pipeline-01',type:'3d',title:'From asset to engine',category:'Technical',image:'solution-for-devs_01_UQV6U55twKC.png',description:'A technical recording from the Solution for Devs series, showing a material workflow in Unreal Engine.',role:'Technical workflow',tools:'Unreal Engine',embed:'https://www-ccv.adobe.io/v1/player/ccv/UQV6U55twKC/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View'},
 {id:'sodhi-brand',type:'design',title:'deExpressions identity',category:'Brand identity',image:'sodhi-brand.jpg',description:'Logo and brand identity work from my graphic design portfolio.',role:'Graphic design',tools:'Brand identity'},
 {id:'typography',type:'design',title:'Type with a voice',category:'Typography',image:'typography.jpg',description:'A typographic composition from the existing design collection.',role:'Typography & composition',tools:'Graphic design'},
 {id:'honey-packaging',type:'design',title:'Natural Honey',category:'Packaging',image:'honey-packaging.jpg',description:'A product label design from the packaging and print collection.',role:'Label design',tools:'Packaging & print'},
 {id:'judge-edit',type:'video',title:'In the judge’s chair',category:'Television editing',image:'judge-edit.png',description:'Judge Edit 1, from the television editing collection. The original video is hosted on Google Drive.',role:'Video editing',tools:'Editing & post-production',embed:'https://drive.google.com/file/d/1DmkwXZgjdMpDQQ53IT8jAP7psUdJhGqc/preview'},
 {id:'motion-graphics',type:'video',title:'Graphic, in motion',category:'Motion graphics',image:'motion-graphics.png',description:'Motion Graphic 1, a piece from the motion graphics collection.',role:'Motion graphics',tools:'Motion design',embed:'https://drive.google.com/file/d/10yMgbCK6-gNbVgX2IN7DM0q3jnVEiCxn/preview'},
 {id:'short-film',type:'video',title:'A short story',category:'Short film',image:'short-film.png',description:'A short-film competition entry featuring acting and editing work.',role:'Acting & editing',tools:'Short-film production',embed:'https://www-ccv.adobe.io/v1/player/ccv/7tgFVSzNm6a/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View'}
];
window.PRODUCTS = [
 {name:'Meshfill 2.0',tag:'BLENDER',detail:'Grid patches, radial caps & loop bridges.',url:'https://deadhunk.gumroad.com/l/vxigiq',symbol:'▦'},
 {name:'QuadFlow',tag:'BLENDER',detail:'Topology inspection and mesh cleanup.',url:'https://deadhunk.gumroad.com/l/krmazk',symbol:'⌗'},
 {name:'CableCrafter Pro',tag:'BLENDER',detail:'Cables and curve-based modeling.',url:'https://deadhunk.gumroad.com/l/rebvyi',symbol:'∿'},
 {name:'TexelScale',tag:'BLENDER',detail:'A consistent texture density workflow.',url:'https://deadhunk.gumroad.com/l/dvbum',symbol:'▧'},
 {name:'StackMaster',tag:'BLENDER',detail:'Batch modifier operations.',url:'https://deadhunk.gumroad.com/l/sthgv',symbol:'≋'},
 {name:'PurgeCraft',tag:'BLENDER',detail:'Clean up unused scene data.',url:'https://deadhunk.gumroad.com/l/reylp',symbol:'◇'},
 {name:'QuickGround',tag:'BLENDER',detail:'Origin-to-ground raycast tools.',url:'https://deadhunk.gumroad.com/l/wvqno',symbol:'⊥'},
 {name:'QuickID',tag:'BLENDER',detail:'Palette-based material ID painting.',url:'https://deadhunk.gumroad.com/l/kkttmz',symbol:'◫'},
 {name:'GameReady',tag:'BLENDER',detail:'LOD and asset export preparation.',url:'https://deadhunk.gumroad.com/l/bebyo',symbol:'△'}
];
